### ISSUE TITLE
Track reduced rates teleport savings

### ISSUE THREAD

**Issue by deansheather** [Infiziert90/TrackyTrack#2]
It would be great if the plugin could track teleports where the "Reduced Rates I" and "Reduced Rates II" free company buffs saved you money.

- Count of Reduced Rates I and Reduced Rates II teleports
- Total savings (Reduced Rates I is 20% off and Reduced Rates II is 30% off from what I've heard)

I'm willing to contribute this if you're chill with it

**Comment by Infiziert90** [comment]
Do you actually see this reduction in chat?

Because the plugins uses the values that the chat gets

**Comment by deansheather** [comment]
The chat doesn't show the savings, it only shows the actual cost. The plugin could check for the buffs on the character and do some simple math to work out how much was saved.

**Comment by Infiziert90** [comment]
Mmm

If you wanna do a PR, feel free to :)
