### ISSUE TITLE
Issue with Eureka Bunny Chests

### ISSUE THREAD

**Issue by F-a-y-t-h** [Infiziert90/TrackyTrack#3]
It doesn't catch every opened chest; there not much debug text to add any more insight however

**Comment by Infiziert90** [comment]
What chests did you try to open and is your ping rather high?

**Comment by F-a-y-t-h** [comment]
3 gold 3 silver 11 bronze didnt get logged out of 55~ ish total opened
ping generally around 300~350ish

**Comment by Infiziert90** [comment]
Mmm, very likely that the ping is the issue

It basically just starts a timer whenever you are about to finish opening the chest and in that time frame is it expecting the loot to be received
I can increase the time frame a bit

**Comment by Infiziert90** [comment]
Fixed in d5d4106
