### ISSUE TITLE
Suggestion / Request for Feature 

### ISSUE THREAD

**Issue by Skitsoboy13** [Infiziert90/TrackyTrack#6]
I was wondering if youd be able to implement a Triple Triad tracker to tracky.
important features would be:
- NPC played against with sub categories including:
     - Number of Games Played
     - Number of Wins
     - Number of Draws
     - Number of Losses  
     - Cards won and how many of each were won
     - The drop rates of the cards you've won in a percentage form (percent of cards won out of games won)

**Comment by Infiziert90** [comment]
I think this would fit better in a plugin like Triple Triad Buddy
