### ISSUE TITLE
Island Sanctuary Coffers Error.

### ISSUE THREAD

**Issue by Krojack** [Infiziert90/TrackyTrack#7]
Maybe patch 7.1 changed them but I was getting these messages today while opening them. Maybe the coffer ID changed or something.

[Tracky] You've found an unknown coffer drop.
[Tracky] Please consider sending the following information to the dev:
Coffer: 41667 Item: 27976

All other items IDs if needed:
33925
13711
41585
41142
38540
13283
33923
41104
20525
40393
33924
33924

**Comment by Infiziert90** [comment]
Is it possible that you disabled "Gacha Coffers Tracking" in your config?

**Comment by Krojack** [comment]
It is turned off but I don't recall ever doing that. Turned it back on and will report back the next time I open some of these boxes.
